### ISSUE TITLE
zim prompt

### ISSUE THREAD

**Issue by KiteAB** [theniceboy/.config#10]
你在https://www.bilibili.com/video/BV1q7411s7LS 中的终端提示符（也就是→~）叫什么  以前的commit里翻不到了
图（我现在的.zimrc)：![](https://i.loli.net/2020/06/05/WzOLQ2c6qZB3wKE.png)

**Comment by KiteAB** [comment]
还有在上图中  哪个是[~]── ─这个提示符的prompt名称

**Comment by theniceboy** [comment]
gitster，以后这种问题qq问我吧
