### ISSUE TITLE
关于Polybar配置的困惑

### ISSUE THREAD

**Issue by KairuiLiu** [theniceboy/.config#14]
您好，在看您的视频时看到您的PolyBar右上角可以显示系统托盘，请问这个是如何配置的呢，我看到您的config文件right最右面只是一个time

**Comment by theniceboy** [comment]
因为现在我已经不用polybar了。我用的是dwm自带的状态栏

**Comment by Kicamon** [comment]
> 您好，在看您的视频时看到您的PolyBar右上角可以显示系统托盘，请问这个是如何配置的呢，我看到您的config文件right最右面只是一个time

不知道现在你解决了没，polybar的系统托盘是tray这个参数设置的
