### ISSUE TITLE
Hi, I wonder the way you manage your dotfiles

### ISSUE THREAD

**Issue by ysl2** [theniceboy/.config#15]
CW大佬，我这两天尝试了一些dotfiles管理器：chezmoi，GNU stow，和rcm，但是我发现实际体验中，控制粒度不如自己亲手建立软链接。因此想问一下大佬，你是通过什么方式来管理dotfiles的？

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by theniceboy** [comment]
github
