### ISSUE TITLE
Joshuto无法预览和使用默认打开方式

### ISSUE THREAD

**Issue by zhang-yunqi** [theniceboy/.config#19]
你好，我使用了你的Joshuto配置文件，但是无法预览和使用默认打开方式，不知是什么原因。完全没改过

**Comment by deanbear** [comment]
> 你好，我使用了你的Joshuto配置文件，但是无法预览和使用默认打开方式，不知是什么原因。完全没改过

chmod +x [preview_file.sh](https://github.com/theniceboy/.config/blob/master/joshuto/preview_file.sh)

**Comment by zhang-yunqi** [comment]
thanks very much
