### ISSUE TITLE
装完推荐字体之后桌面字体显示不正常

### ISSUE THREAD

**Issue by KyleJKC** [theniceboy/.config#3]
您好，我看了您的**README.md**。下面有个**常用字体推荐**，我手贱给装上了，里面有一些跟我原有的**重复**了，重新安装之后桌面的字体间隙就怪怪的，这要怎么办？（我和在BliBili私信您的是同一个人）
**我执行的安装命令**：
```
yay -S ttf-linux-libertine ttf-inconsolata ttf-joypixels ttf-twemoji-color noto-fonts-emoji ttf-liberation ttf-droid

和

yay -S wqy-bitmapfont wqy-microhei wqy-microhei-lite wqy-zenhei adobe-source-han-mono-cn-fonts adobe-source-han-sans-cn-fonts adobe-source-han-serif-cn-fonts
```
**请您帮帮我，拜托了！**

**Comment by theniceboy** [comment]
卸掉试试吧

**Comment by KyleJKC** [comment]
您好，这些字体正如您说的，都是**要用到的字体**。因此我不能全部卸载，我试过只留下**满足依赖**的字体，卸载其他的字体。可如果这么做，问题并没解决，而且chrome有些字体会无法显示。我试过新建一个用户，如果使用新用户进入桌面的话，问题**全部解决**。说明问题不在字体，家目录里某个配置的问题。但是我并不能一直使用新用户（**重新配置一个用户非常麻烦**）。所以我在想：1.有没有办法能从新用户的家目录里复制一些配置来**替换**我现在的配置？ 2.或者有没有办法能把我的配置直接转移到新用户下？

**Comment by theniceboy** [comment]
配置无非就是几个文件夹，一个`.config`，一个`~/.local/share/fonts`是你用户的字体，你看着对比一下吧。`.config`里面应该是有chrome的配置的。

**Comment by KyleJKC** [comment]
我看了一下两个用户的配置，并进行了一些实验。发现**新用户的字体配置不管怎么调都坏不了**，我的用户**不管怎么调都好不了**。因此我打算更换用户，所以我想问一下**如果我直接把.config文件夹拷到新用户的家目录里的话可不可以直接使用呢？**

**Comment by KyleJKC** [comment]
问题解决了！只是换了一个shell主题之后就ok了，谢谢帮助！
