### ISSUE TITLE
fail to use 'compress' command in ranger

### ISSUE THREAD

**Issue by Unknown-Chinese-User** [theniceboy/.config#4]
my computer can't find compress when using your ranger settings.This is in your .config/ranger/ra.conf at line 462. how can I use ranger to compress files

**Comment by Unknown-Chinese-User** [comment]
I know now. I need to copy the command.py to my folder

**Comment by Unknown-Chinese-User** [comment]
I fixed my last problem by copying your codes in commands.py but when I try the command, the process failed.
what should I do?

**Comment by Unknown-Chinese-User** [comment]
By the way, could I ask that how can I open every type of files via its corresponding way?
For example, I want to open .mp3 with music player, .pdf with pdf reader ,and other text files with vim.

**Comment by theniceboy** [comment]
Pls provide more info

**Comment by Unknown-Chinese-User** [comment]
我重新看了下视频，发现这是在archwiki的命令，然后在wiki找到结果了，打扰了
