### ISSUE TITLE
simplescreenrecorder

### ISSUE THREAD

**Issue by KiteAB** [theniceboy/.config#8]
我把~/.config/picom.conf（里面是空的）替换成了/etc/xdg/picom.conf（默认配置 取消了sogou-qimpanel的阴影）  然后simplescreenrecorder录制闪屏

**Comment by KiteAB** [comment]
@theniceboy

**Comment by KiteAB** [comment]
az

**Comment by theniceboy** [comment]
我的用默认配置就不会闪屏

**Comment by KiteAB** [comment]
az
