### ISSUE TITLE
zsh

### ISSUE THREAD

**Issue by KiteAB** [theniceboy/.config#9]
请问下以前的箭头提示符的非omz的zsh配置的最晚一次commit是哪一次
➜  .zim zsh /tmp/install.zsh
) Git is installed.
) Using Zsh version 5.8
) Your ZIM_HOME is the default one.
) ZIM_HOME already exists, but is empty.
) Zsh is your default shell.
) Prepended Zim template to /home/kiteab/.config/zsh/zimrc
) Copied Zim template to /home/kiteab/.zshrc
) Prepended Zim template to /home/kiteab/.zshenv
) Prepended Zim template to /home/kiteab/.zlogin
Installing modules ...
还有这玩意为啥卡住了

**Comment by theniceboy** [comment]
和本repo无关😂

**Comment by KiteAB** [comment]
是吗  这个repo不是包含zsh吗

**Comment by KiteAB** [comment]
那你zsh目录显示的颜色和多层目录的文件夹名缩写怎么做到的

**Comment by theniceboy** [comment]
prompt？

**Comment by KiteAB** [comment]
> prompt？

yep

**Comment by theniceboy** [comment]
那跟你的prompt有关，是由你选的prompt来决定的

**Comment by KiteAB** [comment]
> 那跟你的prompt有关，是由你选的prompt来决定的

简单来说不就是PS1吗  我没用omz

**Comment by KiteAB** [comment]
你选的啥

**Comment by theniceboy** [comment]
忘了名字。在我的zimrc里

**Comment by KiteAB** [comment]
> 忘了名字。在我的zimrc里
好
